using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Decal.Adapter;
using Decal.Adapter.Wrappers;
using DoThingsBot;
using DoThingsBot.Chat;
using DoThingsBot.FSM;
using DoThingsBot.FSM.States;
using System.Reflection;
using System.Diagnostics;

namespace DoThingsBot {
    public class DoThingsBot {
        public bool isRunning = false;
        public DateTime botStartedAt = DateTime.MinValue;
        
        public Chat.ChatManager _chatManager;

        public Machine _machine;

        public struct PlayerCommand {
            public string PlayerName;
            public string Command;

            public PlayerCommand(string name, string cmd) {
                PlayerName = name;
                Command = cmd;
            }
        }

        public List<PlayerCommand> queue = new List<PlayerCommand>();

        public ItemBundle currentItemBundle;

        private enum DoThingType {
            Tinker
        }

        public DoThingsBot() {
            _chatManager = new Chat.ChatManager();
            _machine = new Machine();

            CoreManager.Current.RenderFrame += new EventHandler<EventArgs>(Current_RenderFrame);
        }

        public void Start() {
            if (!CheckSettings()) {
                Config.Bot.Enabled.Value = false;
                return;
            }
            
            Globals.Stats = new Stats.Stats();

            Util.WriteToChat("DoThingsBot Started");

            CoreManager.Current.Actions.FaceHeading(Config.Bot.DefaultHeading.Value, true);

            isRunning = true;
            botStartedAt = DateTime.UtcNow;
            _machine.Start();

            _machine.ChangeState(new BotIdleState());

            if (Config.Announcements.Enabled.Value == true) {
                if (Config.Announcements.StartupMessage.Value.Length > 0) {
                    ChatManager.AddSpamToChatBox(Config.Announcements.StartupMessage.Value);
                }
            }

            ChatManager.ResetAnnouncementTimer();
            ChatManager.RaiseChatCommandEvent += new EventHandler<ChatCommandEventArgs>(ChatManager_ChatCommand);
            
        }

        private bool CheckSettings() {
            if (Config.Tinkering.Enabled.Value && (Globals.Core.CharacterFilter.CharacterOptions & 0x80000000) == 0) {
                Util.WriteToChat("Error: You must enable the UseCraftSuccessDialog setting!");
                return false;
            }

            return true;
        }

        public void Stop() {
            if (!isRunning)
                return;

            Globals.Stats.globalStats.Save();

            Util.WriteToChat("DoThingsBot stopped");

            ChatManager.RaiseChatCommandEvent -= new EventHandler<ChatCommandEventArgs>(ChatManager_ChatCommand);

            _machine.Stop();
            isRunning = false;

        }

        private bool disposed;

        public void Dispose() {

            CoreManager.Current.RenderFrame -= new EventHandler<EventArgs>(Current_RenderFrame);

            Dispose(true);

            // Use SupressFinalize in case a subclass
            // of this type implements a finalizer.
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing) {
            // If you need thread safety, use a lock around these 
            // operations, as well as in your methods that use the resource.
            if (!disposed) {
                if (disposing) {
                    //Remove the view
                    if (_machine != null)
                        _machine.Dispose();
                }

                // Indicate that the instance has been disposed.
                disposed = true;
            }
        }

        public bool IsLoggedIn = false;

        DateTime lastThought = DateTime.MinValue;

        void Current_RenderFrame(object sender, EventArgs e) {
            try {
                if (!IsLoggedIn) return;

                if (DateTime.UtcNow - lastThought < TimeSpan.FromMilliseconds(50))
                    return;

                lastThought = DateTime.UtcNow;

                Think();

            }
            catch (Exception ex) { Util.LogException(ex); }
        }

        void ChatManager_ChatCommand(object sender, ChatCommandEventArgs e) {
            try {
                if (!IsLoggedIn) return;

                //Util.WriteToChat(String.Format("Got command: '{0}' from '{1}' args: '{2}'", e.Command, e.PlayerName, e.Arguments));
                ProcessCommand(e, false);
            }
            catch (Exception ex) { Util.LogException(ex); }
        }
        
        private static bool IsSubProfile(String s) {
            var profile = Buffs.Buffs.GetProfile(s);
            if (profile == null) return true;
            if (s.ToLower().StartsWith("_")) return true;
            if (profile.IsAutoGenerated()) return true;

            return false;
        }

        void ProcessCommand(ChatCommandEventArgs e, bool skipQueue) {
            if (!_machine.IsRunning) {
                return;
            }

            if (currentItemBundle != null && queue.Count > 0) {
                currentItemBundle = null;
            }

            if (string.IsNullOrEmpty(e.Command)) return;

            switch (e.Command) {
                case "help":
                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                    PrintHelpMessage(e.PlayerName, e.Arguments);
                    break;

                case "about":
                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                    PrintAboutMessage(e.PlayerName, e.Arguments);
                    break;

                case "version":
                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                    PrintAboutMessage(e.PlayerName, e.Arguments);
                    break;

                case "message":
                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                    break;

                case "forcebuff":
                    if ((_machine.IsOrWillBeInState("BotIdleState") || skipQueue) && e.PlayerName == CoreManager.Current.CharacterFilter.Name) {
                        var itemBundle = new ItemBundle();
                        itemBundle.SetForceBuffMode(true);
                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                        _machine.ChangeState(new BotStartState(itemBundle));
                    }
                    break;

                case "skills":
                    if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                        var itemBundle = new ItemBundle(e.PlayerName);
                        currentItemBundle = itemBundle;

                        itemBundle.SetEquipMode(EquipMode.Tinker);
                        itemBundle.SetCraftMode(CraftMode.CheckSkills);
                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                        _machine.ChangeState(new BotStartState(itemBundle));
                    }
                    else {
                        AddToQueue(e.PlayerName, "skills");
                    }
                    break;

                case "whereto":
                    if (!Config.Portals.Enabled.Value) {
                        ChatManager.Tell(e.PlayerName, "My portal bot functionality is currently disabled, sorry!");
                        return;
                    }

                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                    if (string.IsNullOrEmpty(e.Arguments)) {
                        ChatManager.Tell(e.PlayerName, String.Format("I am currently tied to {0} and {1}. '/t {2}, primary' for {0}. '/t {2}, secondary' for {1}",
                            Config.Portals.PrimaryPortalTieLocation.Value,
                            Config.Portals.SecondaryPortalTieLocation.Value,
                            CoreManager.Current.CharacterFilter.Name));

                        var validPortalCommands = Config.Portals.GetValidPortalGemCommands();
                        if (validPortalCommands.Length > 0) {
                            ChatManager.Tell(e.PlayerName, string.Format("I can also summon: {0}", string.Join(", ", validPortalCommands)));
                        }
                    }
                    else {
                        string willSummon = "";

                        if (e.Arguments == Config.Portals.PrimaryPortalExtraCommand.Value) {
                            willSummon = Config.Portals.PrimaryPortalTieLocation.Value;
                        }
                        else if (e.Arguments == Config.Portals.SecondaryPortalExtraCommand.Value) {
                            willSummon = Config.Portals.PrimaryPortalTieLocation.Value;
                        }
                        else if (Config.Portals.PortalGemCommands().ContainsKey(e.Arguments)) {
                            willSummon = Config.Portals.PortalGemCommands()[e.Arguments].Name;
                        }

                        if (string.IsNullOrEmpty(willSummon)) {
                            ChatManager.Tell(e.PlayerName, string.Format("I don't know how to summon '{0}'", e.Arguments));
                        }
                        else {
                            ChatManager.Tell(e.PlayerName, string.Format("If you '/t {0}, {1}' I will summon {2}",
                                Globals.Core.CharacterFilter.Name,
                                e.Arguments,
                                willSummon));
                        }
                    }

                    break;

                case "remove":
                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);
                    RemoveFromQueue(e.PlayerName);
                    break;

                case "primary":
                    if (!Config.Portals.Enabled.Value) {
                        ChatManager.Tell(e.PlayerName, "My portal bot functionality is currently disabled, sorry!");
                        return;
                    }

                    if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                        var itemBundle = new ItemBundle(e.PlayerName);
                        currentItemBundle = itemBundle;
                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                        itemBundle.SetEquipMode(EquipMode.SummonPortal);
                        itemBundle.SetCraftMode(CraftMode.PrimaryPortal);
                        _machine.ChangeState(new BotStartState(itemBundle));
                    }
                    else {
                        AddToQueue(e.PlayerName, "primary");
                    }
                    break;

                case "secondary":
                    if (!Config.Portals.Enabled.Value) {
                        ChatManager.Tell(e.PlayerName, "My portal bot functionality is currently disabled, sorry!");
                        return;
                    }

                    if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                        var itemBundle = new ItemBundle(e.PlayerName);
                        currentItemBundle = itemBundle;
                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                        itemBundle.SetEquipMode(EquipMode.SummonPortal);
                        itemBundle.SetCraftMode(CraftMode.SecondaryPortal);
                        _machine.ChangeState(new BotStartState(itemBundle));
                    }
                    else {
                        AddToQueue(e.PlayerName, "secondary");
                    }
                    break;

                case "tinker":
                    if (!Config.Tinkering.Enabled.Value) {
                        ChatManager.Tell(e.PlayerName, "My tinker bot functionality is currently disabled, sorry!");
                        return;
                    }
                    if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                        var itemBundle = new ItemBundle(e.PlayerName);
                        itemBundle.SetCraftMode(CraftMode.WeaponTinkering);
                        currentItemBundle = itemBundle;
                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                        _machine.ChangeState(new BotStartState(itemBundle));
                    }
                    else {
                        AddToQueue(e.PlayerName, "tinker");
                    }
                    break;

                case "lostitems":
                    if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                        ItemBundle itemBundle = new ItemBundle(e.PlayerName);
                        currentItemBundle = itemBundle;
                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                        if (itemBundle.GetStolenItems().Count <= 0) {
                            ChatManager.Tell(itemBundle.GetOwner(), "I don't think I have any of your items.  If you think this is an error, leave me a message.");
                        }
                        else {
                            itemBundle.SetCraftMode(CraftMode.GiveBackItems);
                            _machine.ChangeState(new BotTradingState(itemBundle));
                        }
                    }
                    else {
                        AddToQueue(e.PlayerName, "lostitems");
                    }
                    break;

                case "go":
                    break;

                case "cancel":
                    break;

                case "profiles":
                    if (!Config.BuffBot.Enabled.Value) {
                        ChatManager.Tell(e.PlayerName, "My buff bot functionality is currently disabled, sorry!");
                        return;
                    }

                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                    var profiles = new List<string>(Buffs.Buffs.profiles.Keys);

                    profiles.RemoveAll(IsSubProfile);

                    var msg = "I support these buff profiles: " + string.Join(", ", profiles.ToArray()) + ".";

                    if (Config.BuffBot.EnableSingleBuffs.Value) {
                        msg += " Singles spells like 'focus warmagic' are also supported.";
                    }

                    Util.WriteToChat(msg);

                    ChatManager.Tell(e.PlayerName, msg);

                    if (Config.BuffBot.EnableTreeStatsBuffs.Value) {
                        ChatManager.Tell(e.PlayerName, "You can tell be 'buff' and I will buff you based on your TreeStats profile.");
                    }

                    break;

                case "buff":
                    if (!Config.BuffBot.EnableTreeStatsBuffs.Value) {
                        ChatManager.Tell(e.PlayerName, "My TreeStats buffing profile functionality is currently disabled, sorry!");
                        return;
                    }
                    if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                        ItemBundle itemBundle = new ItemBundle(e.PlayerName);
                        currentItemBundle = itemBundle;
                        itemBundle.SetCraftMode(CraftMode.Buff);
                        itemBundle.SetEquipMode(EquipMode.Buff);
                        itemBundle.SetBuffProfiles("treestats");

                        Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                        _machine.ChangeState(new BotStartState(itemBundle));
                    }
                    else {
                        AddToQueue(e.PlayerName, "buff");
                    }
                    break;

                default:
                    // check for buff command
                    var allBuffProfiles = Buffs.Buffs.GetAllProfileCommands();

                    if (allBuffProfiles.Contains(e.Command)) {
                        if (!Config.BuffBot.Enabled.Value) {
                            ChatManager.Tell(e.PlayerName, "My Buff Bot functionality is currently disabled, sorry!");
                            return;
                        }

                        var commands = e.Command;
                        if (!string.IsNullOrEmpty(e.Arguments)) {
                            commands += " " + e.Arguments;
                        }

                        if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                            ItemBundle itemBundle = new ItemBundle(e.PlayerName);
                            currentItemBundle = itemBundle;
                            itemBundle.SetCraftMode(CraftMode.Buff);
                            itemBundle.SetEquipMode(EquipMode.Buff);
                            itemBundle.SetBuffProfiles(commands);

                            foreach (var command in commands.Split(' ')) {
                                if (allBuffProfiles.Contains(command)) {
                                    Globals.Stats.AddPlayerCommandIssued(e.PlayerName, command);
                                }
                            }

                            _machine.ChangeState(new BotStartState(itemBundle));
                        }
                        else {
                            AddToQueue(e.PlayerName, commands);
                        }
                        return;
                    }

                    // portal alternative (extra) commands
                    if (e.Command == Config.Portals.PrimaryPortalExtraCommand.Value || e.Command == Config.Portals.SecondaryPortalExtraCommand.Value) {
                        if (!Config.Portals.Enabled.Value) {
                            ChatManager.Tell(e.PlayerName, "My portal bot functionality is currently disabled, sorry!");
                            return;
                        }

                        if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                            var itemBundle = new ItemBundle(e.PlayerName);
                            currentItemBundle = itemBundle;
                            Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                            CraftMode portalMode;

                            if (e.Command == Config.Portals.PrimaryPortalExtraCommand.Value) {
                                portalMode = CraftMode.PrimaryPortal;
                            }
                            else {
                                portalMode = CraftMode.SecondaryPortal;
                            }

                            itemBundle.SetEquipMode(EquipMode.SummonPortal);
                            itemBundle.SetCraftMode(portalMode);
                            _machine.ChangeState(new BotStartState(itemBundle));
                        }
                        else {
                            AddToQueue(e.PlayerName, e.Command);
                        }
                        return;
                    }

                    // portal gem commands
                    if (Config.Portals.PortalGemCommands().ContainsKey(e.Command)) {
                        if (!Config.Portals.Enabled.Value) {
                            ChatManager.Tell(e.PlayerName, "My Portal Bot functionality is currently disabled, sorry!");
                            return;
                        }
                        if (_machine.IsOrWillBeInState("BotIdleState") || skipQueue) {
                            var itemBundle = new ItemBundle(e.PlayerName);
                            currentItemBundle = itemBundle;
                            Globals.Stats.AddPlayerCommandIssued(e.PlayerName, e.Command);

                            itemBundle.SetEquipMode(EquipMode.Idle);
                            itemBundle.SetCraftMode(CraftMode.PortalGem);
                            itemBundle.SetPortalCommand(e.Command);

                            _machine.ChangeState(new BotStartState(itemBundle));
                        }
                        else {
                            AddToQueue(e.PlayerName, e.Command);
                        }
                        return;
                    }
                    
                    if (Config.Bot.RespondToUnknownCommands.Value == true) {
                        ChatManager.Tell(e.PlayerName, "Sorry, I'm a bot and do not understand that command.  Please tell me \"help\" for a list of available commands.");
                    }
                    break;
            }
        }

        void PrintHelpMessage(string playerName, string arguments) {
            switch (arguments) {
                case "tinker":
                    ChatManager.Tell(playerName, "tinker - Tinkers a loot generated item by adding salvage. Make sure you are standing nearby.");
                    break;

                case "lostitems":
                    ChatManager.Tell(playerName, "lostitems - I will check my inventory for any items you may have lost to me. Make sure you are standing nearby.");
                    break;

                case "message":
                    ChatManager.Tell(playerName, "message - Leave me a message. eg: /tell " + CoreManager.Current.CharacterFilter.Name + ", message I think your bot is broken.");
                    break;

                case "remove":
                    ChatManager.Tell(playerName, "remove - Remove yourself from the queue.");
                    break;

                case "skills":
                    ChatManager.Tell(playerName, "skills - I will tell you my current skill levels.");
                    break;

                case "whereto":
                    ChatManager.Tell(playerName, "whereto - I will tell you where my portals are currently tied to.");
                    break;

                case "about":
                    ChatManager.Tell(playerName, "about - I will tell you about my software.");
                    break;

                case "buff":
                    ChatManager.Tell(playerName, "buff - I will automatically buff you based on your TreeStats profile.");
                    break;

                case "profiles":
                    ChatManager.Tell(playerName, "profiles - I will tell you what buff profiles I support.");
                    break;

                default:
                    ChatManager.Tell(playerName, String.Format("I'm a DoThingsBot. Tell me 'tinker' or 'profiles'. Other commands: buff, lostitems, whereto, message, about, version.", Util.GetVersion()));
                    break;

            }
        }

        void PrintAboutMessage(string playerName, string arguments) {
            ChatManager.Tell(playerName, String.Format("I'm a Bot running DoThingsBot v{0}. - Download the plugin yourself at https://gitlab.com/trevis/dothingsbot .", Util.GetVersion()));
        }

        void RemoveFromQueue(string playerName) {
            if (queue.Exists(x => x.Equals(playerName))) {
                int index = queue.FindIndex(x => x.Equals(playerName));
                queue.RemoveAt(index);

                ChatManager.Tell(playerName, "You have been removed from the queue");
            }
            else {
                ChatManager.Tell(playerName, "You aren't in line!");
            }
        }

        public void AddToQueue(string command) {
            queue.Add(new PlayerCommand(CoreManager.Current.CharacterFilter.Name, command));
        }

        public void AddToQueue(string playerName, string command) {
            if (currentItemBundle != null && currentItemBundle.HasOwner() && currentItemBundle.GetOwner() == playerName) {
                ChatManager.Tell(playerName, "I am already helping you.  Please wait until you are finished before issuing more commands.");
                return;
            }

            foreach (PlayerCommand pc in queue) {
                if (pc.PlayerName == playerName) {
                    ChatManager.Tell(playerName, "You are already in line!");
                    return;
                }
            }

            if (_machine.IsOrWillBeInState("BotBuffingState")) {
                ChatManager.Tell(playerName, String.Format("I am currently buffing, but you have been added to the queue."));
            }
            else {
                ChatManager.Tell(playerName, String.Format("I am currently helping someone else, but you have been added to the queue.  There are currently {0} people ahead of you.", queue.Count + 1));
            }

            queue.Add(new PlayerCommand(playerName, command));
        }

        DateTime lastUpdatedUptime = DateTime.UtcNow;
        internal bool needsEquipmentCheck = true;

        void Think() {
            try {
                if (!IsLoggedIn) return;

                
                if (Config.Bot.Enabled.Value == true && !isRunning) {
                    Start();
                }
                else if (Config.Bot.Enabled.Value == false && isRunning) {
                    Stop();
                }

                if (isRunning) {
                    if (_machine.IsInState("BotIdleState")) {
                        if (queue.Count > 0) {
                            ProcessCommand(new ChatCommandEventArgs(queue[0].PlayerName, queue[0].Command, queue[0].Command), true);
                            queue.RemoveAt(0);
                            return;
                        }
                    }

                    ChatManager.Think();

                    _machine.Think();

                    Globals.Stats.Think();
                    Globals.StatsView.Think();
                }
            }
            catch (Exception ex) { Util.LogException(ex); }
        }
    }
}
